engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
- "test/"
- "**/vendor/**"